apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: meriemhamoda/student-app:1.0.0  # Image sur Docker Hub
        imagePullPolicy: Always  # Toujours pull depuis Docker Hub
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: spring-config
        - secretRef:
            name: spring-secret
