apiVersion: v1
data:
  server.port: "8089"
  server.servlet.context-path: /student
  spring.datasource.url: jdbc:mysql://mysql-service:3306/springdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  spring.datasource.username: spring
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.show-sql: "true"
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-17T20:18:46Z"
  name: spring-config
  namespace: devops
  resourceVersion: "19853"
  uid: 5c43061a-ce97-47c9-b2c6-e66a38a771a4
